"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var PlaceType;
(function (PlaceType) {
    PlaceType["accounting"] = "accounting";
    PlaceType["airport"] = "airport";
    PlaceType["amusement_park"] = "amusement_park";
    PlaceType["aquarium"] = "aquarium";
    PlaceType["art_gallery"] = "art_gallery";
    PlaceType["atm"] = "atm";
    PlaceType["bakery"] = "bakery";
    PlaceType["bank"] = "bank";
    PlaceType["bar"] = "bar";
    PlaceType["beauty_salon"] = "beauty_salon";
    PlaceType["bicycle_store"] = "bicycle_store";
    PlaceType["book_store"] = "book_store";
    PlaceType["bowling_alley"] = "bowling_alley";
    PlaceType["bus_station"] = "bus_station";
    PlaceType["cafe"] = "cafe";
    PlaceType["campground"] = "campground";
    PlaceType["car_dealer"] = "car_dealer";
    PlaceType["car_rental"] = "car_rental";
    PlaceType["car_repair"] = "car_repair";
    PlaceType["car_wash"] = "car_wash";
    PlaceType["casino"] = "casino";
    PlaceType["cemetery"] = "cemetery";
    PlaceType["church"] = "church";
    PlaceType["city_hall"] = "city_hall";
    PlaceType["clothing_store"] = "clothing_store";
    PlaceType["convenience_store"] = "convenience_store";
    PlaceType["courthouse"] = "courthouse";
    PlaceType["dentist"] = "dentist";
    PlaceType["department_store"] = "department_store";
    PlaceType["doctor"] = "doctor";
    PlaceType["electrician"] = "electrician";
    PlaceType["electronics_store"] = "electronics_store";
    PlaceType["embassy"] = "embassy";
    // establishment(устарело)
    // finance(устарело)
    PlaceType["fire_station"] = "fire_station";
    PlaceType["florist"] = "florist";
    // food(устарело)
    PlaceType["funeral_home"] = "funeral_home";
    PlaceType["furniture_store"] = "furniture_store";
    PlaceType["gas_station"] = "gas_station";
    // general_contractor(устарело)
    // grocery_or_supermarket(устарело)
    PlaceType["gym"] = "gym";
    PlaceType["hair_care"] = "hair_care";
    PlaceType["hardware_store"] = "hardware_store";
    // health(устарело)
    PlaceType["hindu_temple"] = "hindu_temple";
    PlaceType["home_goods_store"] = "home_goods_store";
    PlaceType["hospital"] = "hospital";
    PlaceType["insurance_agency"] = "insurance_agency";
    PlaceType["jewelry_store"] = "jewelry_store";
    PlaceType["laundry"] = "laundry";
    PlaceType["lawyer"] = "lawyer";
    PlaceType["library"] = "library";
    PlaceType["liquor_store"] = "liquor_store";
    PlaceType["local_government_office"] = "local_government_office";
    PlaceType["locksmith"] = "locksmith";
    PlaceType["lodging"] = "lodging";
    PlaceType["meal_delivery"] = "meal_delivery";
    PlaceType["meal_takeaway"] = "meal_takeaway";
    PlaceType["mosque"] = "mosque";
    PlaceType["movie_rental"] = "movie_rental";
    PlaceType["movie_theater"] = "movie_theater";
    PlaceType["moving_company"] = "moving_company";
    PlaceType["museum"] = "museum";
    PlaceType["night_club"] = "night_club";
    PlaceType["painter"] = "painter";
    PlaceType["park"] = "park";
    PlaceType["parking"] = "parking";
    PlaceType["pet_store"] = "pet_store";
    PlaceType["pharmacy"] = "pharmacy";
    PlaceType["physiotherapist"] = "physiotherapist";
    // place_of_worship(устарело)
    PlaceType["plumber"] = "plumber";
    PlaceType["police"] = "police";
    PlaceType["post_office"] = "post_office";
    PlaceType["real_estate_agency"] = "real_estate_agency";
    PlaceType["restaurant"] = "restaurant";
    PlaceType["roofing_contractor"] = "roofing_contractor";
    PlaceType["rv_park"] = "rv_park";
    PlaceType["school"] = "school";
    PlaceType["shoe_store"] = "shoe_store";
    PlaceType["shopping_mall"] = "shopping_mall";
    PlaceType["spa"] = "spa";
    PlaceType["stadium"] = "stadium";
    PlaceType["storage"] = "storage";
    PlaceType["store"] = "store";
    PlaceType["subway_station"] = "subway_station";
    PlaceType["synagogue"] = "synagogue";
    PlaceType["taxi_stand"] = "taxi_stand";
    PlaceType["train_station"] = "train_station";
    PlaceType["transit_station"] = "transit_station";
    PlaceType["travel_agency"] = "travel_agency";
    PlaceType["university"] = "university";
    PlaceType["veterinary_care"] = "veterinary_care";
    PlaceType["zoo"] = "zoo";
})(PlaceType = exports.PlaceType || (exports.PlaceType = {}));
exports.default = PlaceType;
